
const NaiopData = {
    events: [
        {
            id: 1,
            time: "Wed, Jan 10, 2024 2:00 PM - 3:00 PM MST",
            title: "Edmonton’s New Zoning Bylaw Info Session: Commercial and Industrial Zones",
            heroImage: "hero1.jpg",
            location: "ONLINE",
            description: [
                "Learn about how Edmonton's new Commercial and Industrial Zones support opportunities for businesses, services, recreation, and industrial activities throughout Edmonton.",
                "The City of Edmonton Zoning Bylaw Renewal team will be on hand to take us through some highlights of the zones and answer any questions.",
                "We welcome you to bring along all staff within your company, as well as relevant suppliers and service providers. These sessions will provide a relevant primer for: developers, planners, brokers, and other professional service providers (lawyers, lenders, consultants) working in Edmonton.",
                "This event is virtual and free."
            ],
        },
        {
            id: 2,
            time: "Mon, Jan 15, 2024 2:00 PM - 3:00 PM MST",
            title: "Mixed Use Zones and Multi-Unit Housing Information Session",
            heroImage: "hero2.jpg",
            location: "ONLINE",
            description: [
                "Learn about how Edmonton's new Mixed Use Zones and Residential Zones support opportunities for mixed-use development in nodes and corridors and multi-unit housing.",
                "This session will also cover Zone Modifiers - a new tool to adjust the height, Floor Area Ratio (FAR), and commercial frontage of new development.",
                "The City of Edmonton Zoning Bylaw Renewal team will be on hand to take us through some highlights of the zones and answer any questions.",                
                "We welcome you to bring along all staff within your company, as well as relevant suppliers and service providers. These sessions will provide a relevant primer for: developers, planners, brokers, and other professional service providers (lawyers, lenders, consultants) working in Edmonton.",
                "This event is virtual and free."
            ],
        }
    ],
    memberCompanies: [
        { id: 1, name: "Paucek and Sons" },
        { id: 2, name: "Farrell PLC" },
        { id: 3, name: "Oberbrunner Inc" },
        { id: 4, name: "Lakin Ltd" },
        { id: 5, name: "Prosacco PLC" },
        { id: 6, name: "Pacocha, Stamm and Thompson" },
        { id: 7, name: "Turcotte PLC" },
        { id: 8, name: "Roberts, Abernathy and Boyle" },
        { id: 9, name: "Ernser-Heidenreich" },
        { id: 10, name: "Turner-Rodriguez" },
        { id: 11, name: "Monahan LLC" },
        { id: 12, name: "Harber LLC" },
        { id: 13, name: "Streich, Monahan and Kautzer" },
        { id: 14, name: "Champlin Ltd" },
        { id: 15, name: "Bashirian, Waters and Lesch" },
        { id: 16, name: "Frami Group" },
        { id: 17, name: "Effertz, Erdman and Koch" },
        { id: 18, name: "Koch Inc" },
        { id: 19, name: "Walsh, Paucek and Krajcik" },
        { id: 20, name: "Bednar LLC" },
        { id: 21, name: "Ferry-King" },
        { id: 22, name: "Lang-Hand" },
        { id: 23, name: "Dietrich-Witting" },
        { id: 24, name: "Kutch-Steuber" },
        { id: 25, name: "Bruen, Ullrich and Boyle" },
        { id: 26, name: "Hahn, Rath and Johns" },
        { id: 27, name: "Ebert Inc" },
        { id: 28, name: "Kuhn and Sons" },
        { id: 29, name: "Graham Ltd" },
        { id: 30, name: "Braun-Ferry" },
        { id: 31, name: "Beahan-Brown" },
        { id: 32, name: "Kessler, Brakus and Fadel" },
        { id: 33, name: "Bednar-Witting" },
        { id: 34, name: "Prohaska-Hand" },
        { id: 35, name: "Jakubowski-Predovic" },
        { id: 36, name: "Jacobson Group" },
        { id: 37, name: "Hyatt-Ondricka" },
        { id: 38, name: "Schiller LLC" },
        { id: 39, name: "Stracke Inc" },
        { id: 40, name: "Kuhic, Blanda and Boyle" },
        { id: 41, name: "Feil and Sons" },
        { id: 42, name: "Walsh-Rau" },
        { id: 43, name: "Friesen-Hirthe" },
        { id: 44, name: "Haag-Doyle" },
        { id: 45, name: "Tromp-Kuhic" },
        { id: 46, name: "Jerde-Cronin" },
        { id: 47, name: "Fahey-Raynor" },
        { id: 48, name: "Gibson, Thompson and VonRueden" },
        { id: 49, name: "Howell-Dickens" },
        { id: 50, name: "Rutherford Inc" },
        { id: 51, name: "Hayes-Hansen" },
        { id: 52, name: "Hoppe-Mohr" },
        { id: 53, name: "Klocko-Kautzer" },
        { id: 54, name: "Gerlach Inc" },
        { id: 55, name: "Abernathy-Becker" },
        { id: 56, name: "Price, Konopelski and Rodriguez" },
        { id: 57, name: "Moen LLC" },
        { id: 58, name: "Hayes-Purdy" },
        { id: 59, name: "Sanford Ltd" },
        { id: 60, name: "Yost, Kunde and Rice" },
        { id: 61, name: "Hills, Rowe and Hackett" },
        { id: 62, name: "Towne, Treutel and Dickens" },
        { id: 63, name: "Smith PLC" },
        { id: 64, name: "Jacobs-Wiza" },
        { id: 65, name: "Zieme, Parisian and Breitenberg" },
        { id: 66, name: "Hegmann and Sons" },
        { id: 67, name: "Pfeffer, Spencer and Raynor" },
        { id: 68, name: "Heaney-Mills" },
        { id: 69, name: "Lakin LLC" },
        { id: 70, name: "McCullough, Satterfield and Greenholt" },
        { id: 71, name: "Wyman, Koss and Becker" },
        { id: 72, name: "O'Hara-Hane" },
        { id: 73, name: "Kautzer, D'Amore and Willms" },
        { id: 74, name: "Klein-Vandervort" },
        { id: 75, name: "Yost LLC" },
        { id: 76, name: "Kuhic PLC" },
        { id: 77, name: "Hintz Group" },
        { id: 78, name: "Botsford, Batz and Dickinson" },
        { id: 79, name: "O'Conner Group" },
        { id: 80, name: "Herzog, Schaden and Willms" },
        { id: 81, name: "Kuvalis Ltd" },
        { id: 82, name: "Howell-Powlowski" },
        { id: 83, name: "Christiansen-Mills" },
        { id: 84, name: "Balistreri Ltd" },
        { id: 85, name: "Littel, Schulist and Thiel" },
        { id: 86, name: "Sauer PLC" },
        { id: 87, name: "Huel and Sons" },
        { id: 88, name: "Barrows PLC" },
        { id: 89, name: "Runte-Harris" },
        { id: 90, name: "Wiegand Group" },
        { id: 91, name: "Yost-Carroll" },
        { id: 92, name: "Kerluke PLC" },
        { id: 93, name: "Bosco-Rempel" },
        { id: 94, name: "Swift Group" },
        { id: 95, name: "Weissnat-Gleichner" },
        { id: 96, name: "Kreiger-Pfannerstill" },
        { id: 97, name: "Sipes, Crooks and DuBuque" },
        { id: 98, name: "Pollich PLC" },
        { id: 99, name: "Cruickshank LLC" },
        { id: 100, name: "Frami LLC" }
    ],
}

export default NaiopData;
